### PR TITLE
Add code coverage statistics

### PR DESCRIPTION
**Pull request by ConnorStoneAstro**
Integrates with codecov to display code coverage statistics

### CODE REVIEW

**Comment by ConnorStoneAstro** [comment]
Everything is working, ready for merge!

**Comment by adam-coogan** [comment]
Very cool, thanks for your work on this! Two minor points:

- Is it necessary to have separate actions for the coverage check and tests? They're both calling pytest, so can they be combined somehow?
- Also, have you checked the badge displays correctly? It appears gray on [the PR branch](https://github.com/Ciela-Institute/caustic/tree/addcoverage), but I guess the workflow is set up to run on the `main` branch.

**Comment by ConnorStoneAstro** [comment]
You could combine the tests and checks, but the checks run on Linux MacOS and windows, while the coverage should really only be run once. I could probably combine them but I don't think it's worth the effort. Kind of nice to have them separate since they are different things. Also the code coverage will fail if the coverage decreases, and we don't want that to get misconstrued as the tests failing. 

As for the badge, it only reads from the main branch, so it will only change once the coverage code has been merged. There's probably a way to check ahead of time, but for AutoProf I just merged it and everything worked right away.

**Review by adam-coogan — APPROVED** [review]
Looks great!

**Pull request merged**
